import 'themes.dart';

const List<ThemeDefinition> kAdvanceThemes = [
  ThemeDefinition(id: 'homura_goby',      name: 'ホムラハゼ',           category: TileCategory.creature, gridIndex: 0),
  ThemeDefinition(id: 'barracuda',         name: 'バラクーダ',           category: TileCategory.creature, gridIndex: 1),
  ThemeDefinition(id: 'cave',              name: '洞窟',                 category: TileCategory.scene,    gridIndex: 2),
  ThemeDefinition(id: 'rare_anthias',      name: 'レアハナダイ',         category: TileCategory.creature, gridIndex: 3),
  ThemeDefinition(id: 'boxer_crab',        name: 'キンチャクガニ',       category: TileCategory.creature, gridIndex: 4),
  ThemeDefinition(id: 'courtship_color',   name: '婚姻色・求愛',         category: TileCategory.scene,    gridIndex: 5),
  ThemeDefinition(id: 'whale_shark',       name: 'ジンベエザメ',         category: TileCategory.creature, gridIndex: 6),
  ThemeDefinition(id: 'rockskipper',       name: 'モンツキカエルウオ',   category: TileCategory.creature, gridIndex: 7),
  ThemeDefinition(id: 'thresher_shark',    name: 'ニタリ',               category: TileCategory.creature, gridIndex: 8),
  ThemeDefinition(id: 'cleaning_scene',    name: 'クリーニングシーン',   category: TileCategory.scene,    gridIndex: 9),
  ThemeDefinition(id: 'boxer_shrimp',      name: 'バイオレットボクサーシュリンプ', category: TileCategory.creature, gridIndex: 10),
  ThemeDefinition(id: 'harlequin_shrimp',  name: 'フリソデエビ',         category: TileCategory.creature, gridIndex: 11),
  ThemeDefinition(id: 'advance_free',      name: '⭐ ウルトラレア',      category: TileCategory.creature, gridIndex: 12),
  ThemeDefinition(id: 'hammerhead',        name: 'ハンマーヘッドシャーク', category: TileCategory.creature, gridIndex: 13),
  ThemeDefinition(id: 'wreck',             name: '人工物・沈船',         category: TileCategory.scene,    gridIndex: 14),
  ThemeDefinition(id: 'giant_trevally',    name: 'ギンガメアジ',         category: TileCategory.creature, gridIndex: 15),
  ThemeDefinition(id: 'ribbon_eel',        name: 'ハナヒゲウツボ（幼魚）', category: TileCategory.creature, gridIndex: 16),
  ThemeDefinition(id: 'purple_firefish',   name: 'シコンハタタテハゼ',   category: TileCategory.creature, gridIndex: 17),
  ThemeDefinition(id: 'marine_mammal',     name: '海獣',                 category: TileCategory.creature, gridIndex: 18),
  ThemeDefinition(id: 'spotted_eagle_ray', name: 'マダラトビエイ',       category: TileCategory.creature, gridIndex: 19),
  ThemeDefinition(id: 'spawning',          name: '産卵・抱卵',           category: TileCategory.scene,    gridIndex: 20),
  ThemeDefinition(id: 'giant_trevally2',   name: 'ロウニンアジ',         category: TileCategory.creature, gridIndex: 21),
  ThemeDefinition(id: 'pygmy_seahorse',    name: 'ピグミーシーホース',   category: TileCategory.creature, gridIndex: 22),
  ThemeDefinition(id: 'mandarin_fish2',    name: 'ニシキテグリ',         category: TileCategory.creature, gridIndex: 23),
  ThemeDefinition(id: 'aurora_firefish',   name: 'アケボノハゼ',         category: TileCategory.creature, gridIndex: 24),
];
