import 'themes.dart';

// 石垣ビンゴ
const List<ThemeDefinition> kIshigakiThemes = [
  ThemeDefinition(id: 'ishigaki_manta',            name: 'マンタ',               category: TileCategory.creature, gridIndex: 0),
  ThemeDefinition(id: 'ishigaki_moegi_haze',        name: 'モエギハゼ',           category: TileCategory.creature, gridIndex: 1),
  ThemeDefinition(id: 'ishigaki_coral',             name: 'サンゴの群生',         category: TileCategory.scene,    gridIndex: 2),
  ThemeDefinition(id: 'ishigaki_napoleon',          name: 'ナポレオンフィッシュ', category: TileCategory.creature, gridIndex: 3),
  ThemeDefinition(id: 'ishigaki_deba',              name: 'デバスズメダイの群れ', category: TileCategory.creature, gridIndex: 4),
  ThemeDefinition(id: 'ishigaki_gingame',           name: 'ギンガメアジ',         category: TileCategory.creature, gridIndex: 5),
  ThemeDefinition(id: 'ishigaki_shikon',            name: 'シコンハタタテハゼ',   category: TileCategory.creature, gridIndex: 6),
  ThemeDefinition(id: 'ishigaki_hanabira',          name: 'ハナビラクマノミ',     category: TileCategory.creature, gridIndex: 7),
  ThemeDefinition(id: 'ishigaki_cave',              name: '洞窟・アーチ',         category: TileCategory.scene,    gridIndex: 8),
  ThemeDefinition(id: 'ishigaki_yosuji',            name: 'ヨスジフエダイ',       category: TileCategory.creature, gridIndex: 9),
  ThemeDefinition(id: 'ishigaki_kobushime',         name: 'コブシメ',             category: TileCategory.creature, gridIndex: 10),
  ThemeDefinition(id: 'ishigaki_nakamoto',          name: 'ナカモトイロワケハゼ', category: TileCategory.creature, gridIndex: 11),
  ThemeDefinition(id: 'ishigaki_free',              name: '⭐ 自由枠',            category: TileCategory.creature, gridIndex: 12),
  ThemeDefinition(id: 'ishigaki_isomagurou',        name: 'イソマグロ',           category: TileCategory.creature, gridIndex: 13),
  ThemeDefinition(id: 'ishigaki_rurihoshi',         name: 'ルリホシスズメダイ',   category: TileCategory.creature, gridIndex: 14),
  ThemeDefinition(id: 'ishigaki_akebono',           name: 'アケボノハゼ',         category: TileCategory.creature, gridIndex: 15),
  ThemeDefinition(id: 'ishigaki_white_sand',        name: '白い砂地',             category: TileCategory.scene,    gridIndex: 16),
  ThemeDefinition(id: 'ishigaki_manta_train',       name: 'マンタトレイン',       category: TileCategory.scene,    gridIndex: 17),
  ThemeDefinition(id: 'ishigaki_gurukun',           name: 'グルクンの群れ',       category: TileCategory.creature, gridIndex: 18),
  ThemeDefinition(id: 'ishigaki_ribbon_eel',        name: 'ハナヒゲウツボ（幼魚）', category: TileCategory.creature, gridIndex: 19),
  ThemeDefinition(id: 'ishigaki_sea_turtle',        name: 'アオウミガメ',         category: TileCategory.creature, gridIndex: 20),
  ThemeDefinition(id: 'ishigaki_barracuda',         name: 'バラクーダ',           category: TileCategory.creature, gridIndex: 21),
  ThemeDefinition(id: 'ishigaki_rockskipper',       name: 'モンツキカエルウオ',   category: TileCategory.creature, gridIndex: 22),
  ThemeDefinition(id: 'ishigaki_akanehana',         name: 'アカネハナゴイ',       category: TileCategory.creature, gridIndex: 23),
  ThemeDefinition(id: 'ishigaki_mandarin',          name: 'ニシキテグリ',         category: TileCategory.creature, gridIndex: 24),
];

// 伊豆周辺ビンゴ
const List<ThemeDefinition> kIzuThemes = [
  ThemeDefinition(id: 'izu_kudagonbe',       name: 'クダゴンベ',           category: TileCategory.creature, gridIndex: 0),
  ThemeDefinition(id: 'izu_hammerhead',      name: 'ハンマーヘッドシャーク', category: TileCategory.creature, gridIndex: 1),
  ThemeDefinition(id: 'izu_soft_coral',      name: 'ソフトコーラル',       category: TileCategory.scene,    gridIndex: 2),
  ThemeDefinition(id: 'izu_rare_hanadi',     name: 'レアハナダイ',         category: TileCategory.creature, gridIndex: 3),
  ThemeDefinition(id: 'izu_dango',           name: 'ダンゴウオ',           category: TileCategory.creature, gridIndex: 4),
  ThemeDefinition(id: 'izu_iwashi',          name: 'イワシの群れ',         category: TileCategory.creature, gridIndex: 5),
  ThemeDefinition(id: 'izu_beni_frog',       name: 'ベニカエルアンコウ',   category: TileCategory.creature, gridIndex: 6),
  ThemeDefinition(id: 'izu_mijin',           name: 'ミジンベニハゼ',       category: TileCategory.creature, gridIndex: 7),
  ThemeDefinition(id: 'izu_tobiei',          name: 'トビエイ',             category: TileCategory.creature, gridIndex: 8),
  ThemeDefinition(id: 'izu_tsunozaya',       name: 'ツノザヤウミウシ系',   category: TileCategory.creature, gridIndex: 9),
  ThemeDefinition(id: 'izu_hanatazu',        name: 'ハナタツ',             category: TileCategory.creature, gridIndex: 10),
  ThemeDefinition(id: 'izu_nejirin',         name: 'ネジリンボウ・ヒレネジ', category: TileCategory.creature, gridIndex: 11),
  ThemeDefinition(id: 'izu_free',            name: '⭐ 自由枠',            category: TileCategory.creature, gridIndex: 12),
  ThemeDefinition(id: 'izu_boro',            name: 'ボロカサゴ',           category: TileCategory.creature, gridIndex: 13),
  ThemeDefinition(id: 'izu_seasonal',        name: '季節来遊魚',           category: TileCategory.creature, gridIndex: 14),
  ThemeDefinition(id: 'izu_kumadori',        name: 'クマドリカエルアンコウ', category: TileCategory.creature, gridIndex: 15),
  ThemeDefinition(id: 'izu_akaobihanadi',    name: 'アカオビハナダイ',     category: TileCategory.creature, gridIndex: 16),
  ThemeDefinition(id: 'izu_yasha',           name: 'ヤシャハゼ',           category: TileCategory.creature, gridIndex: 17),
  ThemeDefinition(id: 'izu_kinme',           name: 'キンメモドキの群れ',   category: TileCategory.creature, gridIndex: 18),
  ThemeDefinition(id: 'izu_matou',           name: 'マトウダイ',           category: TileCategory.creature, gridIndex: 19),
  ThemeDefinition(id: 'izu_sakuradai',       name: 'サクラダイ',           category: TileCategory.creature, gridIndex: 20),
  ThemeDefinition(id: 'izu_aori_spawning',   name: 'アオリイカの産卵',     category: TileCategory.scene,    gridIndex: 21),
  ThemeDefinition(id: 'izu_nudibranch',      name: 'ウミウシ',             category: TileCategory.creature, gridIndex: 22),
  ThemeDefinition(id: 'izu_minokasago',      name: 'ミノカサゴ',           category: TileCategory.creature, gridIndex: 23),
  ThemeDefinition(id: 'izu_iro_frog',        name: 'イロカエルアンコウ',   category: TileCategory.creature, gridIndex: 24),
];

// マクロビンゴ
const List<ThemeDefinition> kMacroThemes = [
  ThemeDefinition(id: 'macro_iro_frog',      name: 'イロカエルアンコウ',   category: TileCategory.creature, gridIndex: 0),
  ThemeDefinition(id: 'macro_kumadori',      name: 'クマドリカエルアンコウ', category: TileCategory.creature, gridIndex: 1),
  ThemeDefinition(id: 'macro_beni_frog',     name: 'ベニカエルアンコウ',   category: TileCategory.creature, gridIndex: 2),
  ThemeDefinition(id: 'macro_kamisori',      name: 'カミソリウオ',         category: TileCategory.creature, gridIndex: 3),
  ThemeDefinition(id: 'macro_hanatazu',      name: 'ハナタツ',             category: TileCategory.creature, gridIndex: 4),
  ThemeDefinition(id: 'macro_nishiki_furai', name: 'ニシキフウライウオ',   category: TileCategory.creature, gridIndex: 5),
  ThemeDefinition(id: 'macro_benishibori',   name: 'ベニシボリ',           category: TileCategory.creature, gridIndex: 6),
  ThemeDefinition(id: 'macro_torafu',        name: 'トラフケボリ',         category: TileCategory.creature, gridIndex: 7),
  ThemeDefinition(id: 'macro_jawfish',       name: 'ジョーフィッシュ',     category: TileCategory.creature, gridIndex: 8),
  ThemeDefinition(id: 'macro_kokeginpo',     name: 'コケギンポ',           category: TileCategory.creature, gridIndex: 9),
  ThemeDefinition(id: 'macro_minami_hako',   name: 'ミナミハコフグ幼魚',   category: TileCategory.creature, gridIndex: 10),
  ThemeDefinition(id: 'macro_hotate_umi',    name: 'ホタテウミヘビ',       category: TileCategory.creature, gridIndex: 11),
  ThemeDefinition(id: 'macro_amami',         name: 'アマミスズメダイ',     category: TileCategory.creature, gridIndex: 12),
  ThemeDefinition(id: 'macro_umiteng',       name: 'ウミテング',           category: TileCategory.creature, gridIndex: 13),
  ThemeDefinition(id: 'macro_isokasago',     name: 'イソカサゴ',           category: TileCategory.creature, gridIndex: 14),
  ThemeDefinition(id: 'macro_satsuma',       name: 'サツマカサゴ',         category: TileCategory.creature, gridIndex: 15),
  ThemeDefinition(id: 'macro_gonzui',        name: 'ゴンズイ',             category: TileCategory.creature, gridIndex: 16),
  ThemeDefinition(id: 'macro_shimofuri',     name: 'シモフリタナバタウオ', category: TileCategory.creature, gridIndex: 17),
  ThemeDefinition(id: 'macro_youji',         name: 'ヨウジウオ',           category: TileCategory.creature, gridIndex: 18),
  ThemeDefinition(id: 'macro_oiran_youji',   name: 'オイランヨウジ',       category: TileCategory.creature, gridIndex: 19),
  ThemeDefinition(id: 'macro_tengu',         name: 'テングカワハギ',       category: TileCategory.creature, gridIndex: 20),
  ThemeDefinition(id: 'macro_houbo',         name: 'ホウボウ',             category: TileCategory.creature, gridIndex: 21),
  ThemeDefinition(id: 'macro_tatsu_itoko',   name: 'タツノイトコ',         category: TileCategory.creature, gridIndex: 22),
  ThemeDefinition(id: 'macro_nokogiri',      name: 'ノコギリハギ幼魚',     category: TileCategory.creature, gridIndex: 23),
  ThemeDefinition(id: 'macro_tsuyu',         name: 'ツユベラ幼魚',         category: TileCategory.creature, gridIndex: 24),
];

// ワイドビンゴ
const List<ThemeDefinition> kWideThemes = [
  ThemeDefinition(id: 'wide_black_manta',    name: 'ブラックマンタ',         category: TileCategory.creature, gridIndex: 0),
  ThemeDefinition(id: 'wide_terrain',        name: '地形',                   category: TileCategory.scene,    gridIndex: 1),
  ThemeDefinition(id: 'wide_hanadi_school',  name: 'ハナダイの群れ',         category: TileCategory.creature, gridIndex: 2),
  ThemeDefinition(id: 'wide_shiro_wani',     name: 'シロワニ・イタチザメ',   category: TileCategory.creature, gridIndex: 3),
  ThemeDefinition(id: 'wide_white_sand',     name: '白い砂地',               category: TileCategory.scene,    gridIndex: 4),
  ThemeDefinition(id: 'wide_light_curtain',  name: '光のカーテン',           category: TileCategory.scene,    gridIndex: 5),
  ThemeDefinition(id: 'wide_sukashi',        name: 'スカシテンジクダイ',     category: TileCategory.creature, gridIndex: 6),
  ThemeDefinition(id: 'wide_under_boat',     name: '船下',                   category: TileCategory.scene,    gridIndex: 7),
  ThemeDefinition(id: 'wide_koban',          name: 'コバンザメ',             category: TileCategory.creature, gridIndex: 8),
  ThemeDefinition(id: 'wide_soft_coral',     name: 'ソフトコーラルの群生',   category: TileCategory.scene,    gridIndex: 9),
  ThemeDefinition(id: 'wide_sun',            name: '太陽入り',               category: TileCategory.scene,    gridIndex: 10),
  ThemeDefinition(id: 'wide_murehatate',     name: 'ムレハタタテダイの群れ', category: TileCategory.creature, gridIndex: 11),
  ThemeDefinition(id: 'wide_free',           name: '⭐ 自由枠',              category: TileCategory.scene,    gridIndex: 12),
  ThemeDefinition(id: 'wide_macro',          name: 'ワイドマクロ',           category: TileCategory.scene,    gridIndex: 13),
  ThemeDefinition(id: 'wide_manbou',         name: 'マンボウ',               category: TileCategory.creature, gridIndex: 14),
  ThemeDefinition(id: 'wide_fish_wall',      name: '魚の壁',                 category: TileCategory.scene,    gridIndex: 15),
  ThemeDefinition(id: 'wide_diver',          name: 'ダイバー入り',           category: TileCategory.scene,    gridIndex: 16),
  ThemeDefinition(id: 'wide_isobana',        name: 'イソバナ・ウミウチワ',   category: TileCategory.scene,    gridIndex: 17),
  ThemeDefinition(id: 'wide_whale_shark',    name: 'ジンベエザメ',           category: TileCategory.creature, gridIndex: 18),
  ThemeDefinition(id: 'wide_hansuimen',      name: '半水面',                 category: TileCategory.scene,    gridIndex: 19),
  ThemeDefinition(id: 'wide_tornado',        name: 'トルネード',             category: TileCategory.scene,    gridIndex: 20),
  ThemeDefinition(id: 'wide_reflection',     name: '水面リフレクション',     category: TileCategory.scene,    gridIndex: 21),
  ThemeDefinition(id: 'wide_azahata',        name: 'アザハタ',               category: TileCategory.creature, gridIndex: 22),
  ThemeDefinition(id: 'wide_dolphin',        name: 'イルカ',                 category: TileCategory.creature, gridIndex: 23),
  ThemeDefinition(id: 'wide_great_reef',     name: '大珊瑚礁',               category: TileCategory.scene,    gridIndex: 24),
];

// 串本周辺ビンゴ
const List<ThemeDefinition> kKushimotoThemes = [
  ThemeDefinition(id: 'kushi_azahata',       name: 'アザハタ',                   category: TileCategory.creature, gridIndex: 0),
  ThemeDefinition(id: 'kushi_pink_squad',    name: 'ピンクスクワッドロブスター', category: TileCategory.creature, gridIndex: 1),
  ThemeDefinition(id: 'kushi_hatanpo',       name: 'ハタンポの群れ',             category: TileCategory.creature, gridIndex: 2),
  ThemeDefinition(id: 'kushi_akebono',       name: 'アケボノハゼ',               category: TileCategory.creature, gridIndex: 3),
  ThemeDefinition(id: 'kushi_osansho',       name: 'オオサンショウウオ',         category: TileCategory.creature, gridIndex: 4),
  ThemeDefinition(id: 'kushi_kagokaki',      name: 'カゴカキダイの群れ',         category: TileCategory.creature, gridIndex: 5),
  ThemeDefinition(id: 'kushi_orangutan',     name: 'オラウータンクラブ',         category: TileCategory.creature, gridIndex: 6),
  ThemeDefinition(id: 'kushi_harisenbou',    name: 'ハリセンボン',               category: TileCategory.creature, gridIndex: 7),
  ThemeDefinition(id: 'kushi_shizumi',       name: 'シズミイソコケギンポ',       category: TileCategory.creature, gridIndex: 8),
  ThemeDefinition(id: 'kushi_minami_hako',   name: 'ミナミハコフグ幼魚',         category: TileCategory.creature, gridIndex: 9),
  ThemeDefinition(id: 'kushi_kujaku',        name: 'クジャクケヤリ',             category: TileCategory.creature, gridIndex: 10),
  ThemeDefinition(id: 'kushi_hotate_tsuno',  name: 'ホタテツノハゼ',             category: TileCategory.creature, gridIndex: 11),
  ThemeDefinition(id: 'kushi_free',          name: '⭐ 自由枠',                  category: TileCategory.creature, gridIndex: 12),
  ThemeDefinition(id: 'kushi_hanaika',       name: 'ハナイカ',                   category: TileCategory.creature, gridIndex: 13),
  ThemeDefinition(id: 'kushi_arch',          name: 'アーチ・洞窟',               category: TileCategory.scene,    gridIndex: 14),
  ThemeDefinition(id: 'kushi_iwa_ana',       name: 'イワアナコケギンポ',         category: TileCategory.creature, gridIndex: 15),
  ThemeDefinition(id: 'kushi_hourai',        name: 'ホウライヒメジの群れ',       category: TileCategory.creature, gridIndex: 16),
  ThemeDefinition(id: 'kushi_mino_iso',      name: 'ミノイソギンチャク',         category: TileCategory.creature, gridIndex: 17),
  ThemeDefinition(id: 'kushi_oomon_frog',    name: 'オオモンカエルアンコウ',     category: TileCategory.creature, gridIndex: 18),
  ThemeDefinition(id: 'kushi_kikuchi',       name: 'キクチカニダマシ',           category: TileCategory.creature, gridIndex: 19),
  ThemeDefinition(id: 'kushi_umiusagi',      name: 'ウミウサギ',                 category: TileCategory.creature, gridIndex: 20),
  ThemeDefinition(id: 'kushi_zara',          name: 'ザラカイメンカクレエビ',     category: TileCategory.creature, gridIndex: 21),
  ThemeDefinition(id: 'kushi_toshima',       name: 'トウシマコケギンポ',         category: TileCategory.creature, gridIndex: 22),
  ThemeDefinition(id: 'kushi_kogane',        name: 'コガネスズメダイの群れ',     category: TileCategory.creature, gridIndex: 23),
  ThemeDefinition(id: 'kushi_araiso',        name: 'アライソコケギンポ',         category: TileCategory.creature, gridIndex: 24),
];

// 柏島・愛南ビンゴ
const List<ThemeDefinition> kKashiwajimaThemes = [
  ThemeDefinition(id: 'kashi_iso_kompei',    name: 'イソコンペイトウガニ',       category: TileCategory.creature, gridIndex: 0),
  ThemeDefinition(id: 'kashi_akebono',       name: 'アケボノハゼ',               category: TileCategory.creature, gridIndex: 1),
  ThemeDefinition(id: 'kashi_naginata',      name: 'ナギナタハゼ',               category: TileCategory.creature, gridIndex: 2),
  ThemeDefinition(id: 'kashi_homura',        name: 'ホムラハゼ',                 category: TileCategory.creature, gridIndex: 3),
  ThemeDefinition(id: 'kashi_panda_daruma',  name: 'パンダダルマハゼ',           category: TileCategory.creature, gridIndex: 4),
  ThemeDefinition(id: 'kashi_kiiro_sango',   name: 'キイロサンゴハゼ',           category: TileCategory.creature, gridIndex: 5),
  ThemeDefinition(id: 'kashi_futairo_sango', name: 'フタイロサンゴハゼ',         category: TileCategory.creature, gridIndex: 6),
  ThemeDefinition(id: 'kashi_ade_utsubo',    name: 'アデウツボ',                 category: TileCategory.creature, gridIndex: 7),
  ThemeDefinition(id: 'kashi_sarasa_hata',   name: 'サラサハタ幼魚',             category: TileCategory.creature, gridIndex: 8),
  ThemeDefinition(id: 'kashi_hohosuj',       name: 'ホホスジタルミ幼魚',         category: TileCategory.creature, gridIndex: 9),
  ThemeDefinition(id: 'kashi_aosahagi',      name: 'アオサハギ幼魚',             category: TileCategory.creature, gridIndex: 10),
  ThemeDefinition(id: 'kashi_violet_boxer',  name: 'バイオレットボクサーシュリンプ', category: TileCategory.creature, gridIndex: 11),
  ThemeDefinition(id: 'kashi_kinchaaku',     name: 'キンチャクガニ',             category: TileCategory.creature, gridIndex: 12),
  ThemeDefinition(id: 'kashi_pygmy',         name: 'ピグミーシーホース',         category: TileCategory.creature, gridIndex: 13),
  ThemeDefinition(id: 'kashi_shikon',        name: 'シコンハタタテハゼ',         category: TileCategory.creature, gridIndex: 14),
  ThemeDefinition(id: 'kashi_bobsan',        name: 'ボブサンウミウシ',           category: TileCategory.creature, gridIndex: 15),
  ThemeDefinition(id: 'kashi_inazuma',       name: 'イナズマヒカリイシモチ',     category: TileCategory.creature, gridIndex: 16),
  ThemeDefinition(id: 'kashi_ookawari',      name: 'オオカワリイソギンチャク',   category: TileCategory.creature, gridIndex: 17),
  ThemeDefinition(id: 'kashi_beni_frog',     name: 'ベニカエルアンコウ',         category: TileCategory.creature, gridIndex: 18),
  ThemeDefinition(id: 'kashi_umiushi_kakure',name: 'ウミウシカクレエビ',         category: TileCategory.creature, gridIndex: 19),
  ThemeDefinition(id: 'kashi_hanaika',       name: 'ハナイカ',                   category: TileCategory.creature, gridIndex: 20),
  ThemeDefinition(id: 'kashi_hotate_tsuno',  name: 'ホタテツノハゼ',             category: TileCategory.creature, gridIndex: 21),
  ThemeDefinition(id: 'kashi_oshare_hanadi', name: 'オシャレハナダイ',           category: TileCategory.creature, gridIndex: 22),
  ThemeDefinition(id: 'kashi_yokoebi',       name: 'ヨコエビ',                   category: TileCategory.creature, gridIndex: 23),
  ThemeDefinition(id: 'kashi_coleman',       name: 'コールマンシュリンプ',       category: TileCategory.creature, gridIndex: 24),
];

// 深場・底地ビンゴ
const List<ThemeDefinition> kDeepThemes = [
  ThemeDefinition(id: 'deep_suji_kuro',      name: 'スジクロユリハゼ',     category: TileCategory.creature, gridIndex: 0),
  ThemeDefinition(id: 'deep_tengai',         name: 'テンガイハタ',         category: TileCategory.creature, gridIndex: 1),
  ThemeDefinition(id: 'deep_beni_hanadi',    name: 'ベニハナダイ',         category: TileCategory.creature, gridIndex: 2),
  ThemeDefinition(id: 'deep_black_bg',       name: '黒抜き',               category: TileCategory.scene,    gridIndex: 3),
  ThemeDefinition(id: 'deep_akagutu',        name: 'アカグツ',             category: TileCategory.creature, gridIndex: 4),
  ThemeDefinition(id: 'deep_asahi_gani',     name: 'アサヒガニ',           category: TileCategory.creature, gridIndex: 5),
  ThemeDefinition(id: 'deep_sumire',         name: 'スミレナガハナダイ',   category: TileCategory.creature, gridIndex: 6),
  ThemeDefinition(id: 'deep_houbo',          name: 'ホウボウ',             category: TileCategory.creature, gridIndex: 7),
  ThemeDefinition(id: 'deep_snoot',          name: 'スヌート',             category: TileCategory.scene,    gridIndex: 8),
  ThemeDefinition(id: 'deep_oguro_kuro',     name: 'オグロクロユリハゼ',   category: TileCategory.creature, gridIndex: 9),
  ThemeDefinition(id: 'deep_samon',          name: '砂紋',                 category: TileCategory.scene,    gridIndex: 10),
  ThemeDefinition(id: 'deep_kishima',        name: 'キシマハナダイ',       category: TileCategory.creature, gridIndex: 11),
  ThemeDefinition(id: 'deep_free',           name: '⭐ 自由枠',            category: TileCategory.creature, gridIndex: 12),
  ThemeDefinition(id: 'deep_kasuzame',       name: 'カスザメ',             category: TileCategory.creature, gridIndex: 13),
  ThemeDefinition(id: 'deep_houseki',        name: 'ホウセキカサゴ',       category: TileCategory.creature, gridIndex: 14),
  ThemeDefinition(id: 'deep_asahi_hana',     name: 'アサヒハナゴイ',       category: TileCategory.creature, gridIndex: 15),
  ThemeDefinition(id: 'deep_umi_tosaka',     name: '大ウミトサカ',         category: TileCategory.scene,    gridIndex: 16),
  ThemeDefinition(id: 'deep_madara_hanadi',  name: 'マダラハナダイ',       category: TileCategory.creature, gridIndex: 17),
  ThemeDefinition(id: 'deep_ryugu',          name: 'リュウグウノツカイ',   category: TileCategory.creature, gridIndex: 18),
  ThemeDefinition(id: 'deep_suji_hanadi',    name: 'スジハナダイ',         category: TileCategory.creature, gridIndex: 19),
  ThemeDefinition(id: 'deep_sakuradai',      name: 'サクラダイ',           category: TileCategory.creature, gridIndex: 20),
  ThemeDefinition(id: 'deep_kianko',         name: 'キアンコウ',           category: TileCategory.creature, gridIndex: 21),
  ThemeDefinition(id: 'deep_fuchidori',      name: 'フチドリハナダイ',     category: TileCategory.creature, gridIndex: 22),
  ThemeDefinition(id: 'deep_oshare',         name: 'オシャレハナダイ',     category: TileCategory.creature, gridIndex: 23),
  ThemeDefinition(id: 'deep_akaboshi_hana',  name: 'アカボシハナゴイ',     category: TileCategory.creature, gridIndex: 24),
];

// ハナダイビンゴ
const List<ThemeDefinition> kHanadiThemes = [
  ThemeDefinition(id: 'hanadi_kingyo',       name: 'キンギョハナダイ',         category: TileCategory.creature, gridIndex: 0),
  ThemeDefinition(id: 'hanadi_shikishima',   name: 'シキシマハナダイ',         category: TileCategory.creature, gridIndex: 1),
  ThemeDefinition(id: 'hanadi_akane',        name: 'アカネハナゴイ',           category: TileCategory.creature, gridIndex: 2),
  ThemeDefinition(id: 'hanadi_kourin',       name: 'コウリンハナダイ',         category: TileCategory.creature, gridIndex: 3),
  ThemeDefinition(id: 'hanadi_sakura',       name: 'サクラダイ',               category: TileCategory.creature, gridIndex: 4),
  ThemeDefinition(id: 'hanadi_suji',         name: 'スジハナダイ',             category: TileCategory.creature, gridIndex: 5),
  ThemeDefinition(id: 'hanadi_kerama',       name: 'ケラマハナダイ',           category: TileCategory.creature, gridIndex: 6),
  ThemeDefinition(id: 'hanadi_akaboshi',     name: 'アカボシハナゴイ',         category: TileCategory.creature, gridIndex: 7),
  ThemeDefinition(id: 'hanadi_nirami',       name: 'ニラミハナダイ',           category: TileCategory.creature, gridIndex: 8),
  ThemeDefinition(id: 'hanadi_hanagonbe',    name: 'ハナゴンベ',               category: TileCategory.creature, gridIndex: 9),
  ThemeDefinition(id: 'hanadi_oshare',       name: 'オシャレハナダイ',         category: TileCategory.creature, gridIndex: 10),
  ThemeDefinition(id: 'hanadi_fuchidori',    name: 'フチドリハナダイ',         category: TileCategory.creature, gridIndex: 11),
  ThemeDefinition(id: 'hanadi_free',         name: '⭐ 自由枠',                category: TileCategory.creature, gridIndex: 12),
  ThemeDefinition(id: 'hanadi_itohiki',      name: 'イトヒキハナダイ',         category: TileCategory.creature, gridIndex: 13),
  ThemeDefinition(id: 'hanadi_asahi',        name: 'アサヒハナゴイ',           category: TileCategory.creature, gridIndex: 14),
  ThemeDefinition(id: 'hanadi_naga',         name: 'ナガハナダイ',             category: TileCategory.creature, gridIndex: 15),
  ThemeDefinition(id: 'hanadi_akaobihanadi', name: 'アカオビハナダイ',         category: TileCategory.creature, gridIndex: 16),
  ThemeDefinition(id: 'hanadi_shirobi',      name: 'シロオビハナダイ',         category: TileCategory.creature, gridIndex: 17),
  ThemeDefinition(id: 'hanadi_bonin',        name: 'ボニンハナダイ',           category: TileCategory.creature, gridIndex: 18),
  ThemeDefinition(id: 'hanadi_itohiki_ko',   name: 'イトヒキコハクハナダイ',   category: TileCategory.creature, gridIndex: 19),
  ThemeDefinition(id: 'hanadi_kashiwa',      name: 'カシワハナダイ',           category: TileCategory.creature, gridIndex: 20),
  ThemeDefinition(id: 'hanadi_madara',       name: 'マダラハナダイ',           category: TileCategory.creature, gridIndex: 21),
  ThemeDefinition(id: 'hanadi_futairo',      name: 'フタイロハナゴイ',         category: TileCategory.creature, gridIndex: 22),
  ThemeDefinition(id: 'hanadi_sumire',       name: 'スミレナガハナダイ',       category: TileCategory.creature, gridIndex: 23),
  ThemeDefinition(id: 'hanadi_kishima',      name: 'キシマハナダイ',           category: TileCategory.creature, gridIndex: 24),
];

// ウミウシビンゴ（イロウミウシ）
const List<ThemeDefinition> kNudibranchIroThemes = [
  ThemeDefinition(id: 'nudi_iro_nishiki',    name: 'ニシキウミウシ',           category: TileCategory.creature, gridIndex: 0),
  ThemeDefinition(id: 'nudi_iro_renge',      name: 'レンゲウミウシ',           category: TileCategory.creature, gridIndex: 1),
  ThemeDefinition(id: 'nudi_iro_shirotasuki',name: 'シロタスキウミウシ',       category: TileCategory.creature, gridIndex: 2),
  ThemeDefinition(id: 'nudi_iro_bobsan',     name: 'ボブサンウミウシ',         category: TileCategory.creature, gridIndex: 3),
  ThemeDefinition(id: 'nudi_iro_shiro',      name: 'シロウミウシ',             category: TileCategory.creature, gridIndex: 4),
  ThemeDefinition(id: 'nudi_iro_zoge',       name: 'ゾウゲイロウミウシ',       category: TileCategory.creature, gridIndex: 5),
  ThemeDefinition(id: 'nudi_iro_miamira',    name: 'ミアミラウミウシ',         category: TileCategory.creature, gridIndex: 6),
  ThemeDefinition(id: 'nudi_iro_shiranami',  name: 'シラナミイロウミウシ',     category: TileCategory.creature, gridIndex: 7),
  ThemeDefinition(id: 'nudi_iro_kuchinashi', name: 'クチナシイロウミウシ',     category: TileCategory.creature, gridIndex: 8),
  ThemeDefinition(id: 'nudi_iro_common',     name: 'コモンウミウシ',           category: TileCategory.creature, gridIndex: 9),
  ThemeDefinition(id: 'nudi_iro_cinderella', name: 'シンデレラウミウシ',       category: TileCategory.creature, gridIndex: 10),
  ThemeDefinition(id: 'nudi_iro_akaten',     name: 'アカテンイロウミウシ',     category: TileCategory.creature, gridIndex: 11),
  ThemeDefinition(id: 'nudi_iro_free',       name: '⭐ 自由枠',                category: TileCategory.creature, gridIndex: 12),
  ThemeDefinition(id: 'nudi_iro_mizore',     name: 'ミゾレウミウシ',           category: TileCategory.creature, gridIndex: 13),
  ThemeDefinition(id: 'nudi_iro_akanesasu',  name: 'アカネサスウミウシ',       category: TileCategory.creature, gridIndex: 14),
  ThemeDefinition(id: 'nudi_iro_madara',     name: 'マダライロウミウシ',       category: TileCategory.creature, gridIndex: 15),
  ThemeDefinition(id: 'nudi_iro_hoshizora',  name: 'ホシゾラウミウシ',         category: TileCategory.creature, gridIndex: 16),
  ThemeDefinition(id: 'nudi_iro_senten',     name: 'センテンイロウミウシ',     category: TileCategory.creature, gridIndex: 17),
  ThemeDefinition(id: 'nudi_iro_caramel',    name: 'キャラメルウミウシ',       category: TileCategory.creature, gridIndex: 18),
  ThemeDefinition(id: 'nudi_iro_sarasa',     name: 'サラサウミウシ',           category: TileCategory.creature, gridIndex: 19),
  ThemeDefinition(id: 'nudi_iro_kiberi',     name: 'キベリアカイロウミウシ',   category: TileCategory.creature, gridIndex: 20),
  ThemeDefinition(id: 'nudi_iro_shirotae',   name: 'シロタエイロウミウシ',     category: TileCategory.creature, gridIndex: 21),
  ThemeDefinition(id: 'nudi_iro_kurasaki',   name: 'クラサキウミウシ',         category: TileCategory.creature, gridIndex: 22),
  ThemeDefinition(id: 'nudi_iro_heri',       name: 'ヘリシロイロウミウシ',     category: TileCategory.creature, gridIndex: 23),
  ThemeDefinition(id: 'nudi_iro_monja',      name: 'モンジャウミウシ',         category: TileCategory.creature, gridIndex: 24),
];

// ウミウシビンゴ（イロウミウシ以外）
const List<ThemeDefinition> kNudibranchOtherThemes = [
  ThemeDefinition(id: 'nudi_other_pikachu',  name: 'ピカチュウ（ウデフリツノザヤウミウシ）', category: TileCategory.creature, gridIndex: 0),
  ThemeDefinition(id: 'nudi_other_midori',   name: 'ミドリガイ系',             category: TileCategory.creature, gridIndex: 1),
  ThemeDefinition(id: 'nudi_other_sagami',   name: 'サガミリュウグウウミウシ', category: TileCategory.creature, gridIndex: 2),
  ThemeDefinition(id: 'nudi_other_kompei',   name: 'コンペイトウウミウシ',     category: TileCategory.creature, gridIndex: 3),
  ThemeDefinition(id: 'nudi_other_buchi',    name: 'ブチウミウシ',             category: TileCategory.creature, gridIndex: 4),
  ThemeDefinition(id: 'nudi_other_beni',     name: 'ベニシボリ',               category: TileCategory.creature, gridIndex: 5),
  ThemeDefinition(id: 'nudi_other_sakishima',name: 'サキシマミノウミウシ',     category: TileCategory.creature, gridIndex: 6),
  ThemeDefinition(id: 'nudi_other_umikocho', name: 'ウミコチョウ系',           category: TileCategory.creature, gridIndex: 7),
  ThemeDefinition(id: 'nudi_other_kuchinashi_tsuno', name: 'クチナシツノザヤウミウシ', category: TileCategory.creature, gridIndex: 8),
  ThemeDefinition(id: 'nudi_other_hiodoshi', name: 'ヒオドシユビウミウシ',     category: TileCategory.creature, gridIndex: 9),
  ThemeDefinition(id: 'nudi_other_mikado',   name: 'ミカドウミウシ',           category: TileCategory.creature, gridIndex: 10),
  ThemeDefinition(id: 'nudi_other_gomafu',   name: 'ゴマフビロードウミウシ',   category: TileCategory.creature, gridIndex: 11),
  ThemeDefinition(id: 'nudi_other_free',     name: '⭐ 自由枠',                category: TileCategory.creature, gridIndex: 12),
  ThemeDefinition(id: 'nudi_other_mo',       name: 'モウミウシ系',             category: TileCategory.creature, gridIndex: 13),
  ThemeDefinition(id: 'nudi_other_rouge',    name: 'ルージュミノウミウシ',     category: TileCategory.creature, gridIndex: 14),
  ThemeDefinition(id: 'nudi_other_kissuji',  name: 'キスジカンテンウミウシ',   category: TileCategory.creature, gridIndex: 15),
  ThemeDefinition(id: 'nudi_other_yukiyama', name: 'ユキヤマウミウシ',         category: TileCategory.creature, gridIndex: 16),
  ThemeDefinition(id: 'nudi_other_kurosuj',  name: 'クロスジリュウグウウミウシ', category: TileCategory.creature, gridIndex: 17),
  ThemeDefinition(id: 'nudi_other_kanna',    name: 'カンナツノザヤウミウシ',   category: TileCategory.creature, gridIndex: 18),
  ThemeDefinition(id: 'nudi_other_otome',    name: 'オトメウミウシ系',         category: TileCategory.creature, gridIndex: 19),
  ThemeDefinition(id: 'nudi_other_conshib',  name: 'コンシボリガイ',           category: TileCategory.creature, gridIndex: 20),
  ThemeDefinition(id: 'nudi_other_pineapple',name: 'パイナップルウミウシ',     category: TileCategory.creature, gridIndex: 21),
  ThemeDefinition(id: 'nudi_other_kiibo',    name: 'キイボキヌハダウミウシ',   category: TileCategory.creature, gridIndex: 22),
  ThemeDefinition(id: 'nudi_other_hiro',     name: 'ヒロウミウシ',             category: TileCategory.creature, gridIndex: 23),
  ThemeDefinition(id: 'nudi_other_shimofuri',name: 'シモフリカメサンウミウシ', category: TileCategory.creature, gridIndex: 24),
];

// ハゼビンゴ
const List<ThemeDefinition> kGobyBingoThemes = [
  ThemeDefinition(id: 'goby_neji',           name: 'ネジ・ヒレネジ',           category: TileCategory.creature, gridIndex: 0),
  ThemeDefinition(id: 'goby_moegi',          name: 'モエギハゼ',               category: TileCategory.creature, gridIndex: 1),
  ThemeDefinition(id: 'goby_garasu',         name: 'ガラスハゼ',               category: TileCategory.creature, gridIndex: 2),
  ThemeDefinition(id: 'goby_homura',         name: 'ホムラハゼ',               category: TileCategory.creature, gridIndex: 3),
  ThemeDefinition(id: 'goby_nichirin',       name: 'ニチリンダテハゼ',         category: TileCategory.creature, gridIndex: 4),
  ThemeDefinition(id: 'goby_sango',          name: 'サンゴハゼ',               category: TileCategory.creature, gridIndex: 5),
  ThemeDefinition(id: 'goby_akebono',        name: 'アケボノハゼ',             category: TileCategory.creature, gridIndex: 6),
  ThemeDefinition(id: 'goby_okinawa_beni',   name: 'オキナワベニハゼ',         category: TileCategory.creature, gridIndex: 7),
  ThemeDefinition(id: 'goby_kani',           name: 'カニハゼ',                 category: TileCategory.creature, gridIndex: 8),
  ThemeDefinition(id: 'goby_oguro_kuro',     name: 'オグロクロユリハゼ',       category: TileCategory.creature, gridIndex: 9),
  ThemeDefinition(id: 'goby_yasha',          name: 'ヤシャハゼ',               category: TileCategory.creature, gridIndex: 10),
  ThemeDefinition(id: 'goby_nakamoto',       name: 'ナカモトイロワケハゼ',     category: TileCategory.creature, gridIndex: 11),
  ThemeDefinition(id: 'goby_free',           name: '⭐ 自由枠',                category: TileCategory.creature, gridIndex: 12),
  ThemeDefinition(id: 'goby_shikon',         name: 'シコンハタタテハゼ',       category: TileCategory.creature, gridIndex: 13),
  ThemeDefinition(id: 'goby_aogi',           name: 'アオギハゼ',               category: TileCategory.creature, gridIndex: 14),
  ThemeDefinition(id: 'goby_umitake',        name: 'ウミタケハゼ',             category: TileCategory.creature, gridIndex: 15),
  ThemeDefinition(id: 'goby_hotate_tsuno',   name: 'ホタテツノハゼ',           category: TileCategory.creature, gridIndex: 16),
  ThemeDefinition(id: 'goby_panda_daruma',   name: 'パンダダルマハゼ',         category: TileCategory.creature, gridIndex: 17),
  ThemeDefinition(id: 'goby_suji_kuro',      name: 'スジクロユリハゼ',         category: TileCategory.creature, gridIndex: 18),
  ThemeDefinition(id: 'goby_kitsune',        name: 'キツネメネジリンボウ',     category: TileCategory.creature, gridIndex: 19),
  ThemeDefinition(id: 'goby_zebra',          name: 'ゼブラハゼ',               category: TileCategory.creature, gridIndex: 20),
  ThemeDefinition(id: 'goby_naginata',       name: 'ナギナタハゼ',             category: TileCategory.creature, gridIndex: 21),
  ThemeDefinition(id: 'goby_akame',          name: 'アカメハゼ',               category: TileCategory.creature, gridIndex: 22),
  ThemeDefinition(id: 'goby_morishita',      name: 'モリシタダテハゼ',         category: TileCategory.creature, gridIndex: 23),
  ThemeDefinition(id: 'goby_odori',          name: 'オドリハゼ',               category: TileCategory.creature, gridIndex: 24),
];

// 甲殻類 定番
const List<ThemeDefinition> kCrustaceanStandardThemes = [
  ThemeDefinition(id: 'crust_st_furisode',   name: 'フリソデエビ',             category: TileCategory.creature, gridIndex: 0),
  ThemeDefinition(id: 'crust_st_akashima',   name: 'アカシマシラヒゲエビ',     category: TileCategory.creature, gridIndex: 1),
  ThemeDefinition(id: 'crust_st_coleman',    name: 'コールマンシュリンプ',     category: TileCategory.creature, gridIndex: 2),
  ThemeDefinition(id: 'crust_st_kinchaaku',  name: 'キンチャクガニ',           category: TileCategory.creature, gridIndex: 3),
  ThemeDefinition(id: 'crust_st_kompei',     name: 'コンペイトウガニ',         category: TileCategory.creature, gridIndex: 4),
  ThemeDefinition(id: 'crust_st_isogimoe',   name: 'イソギンチャクモエビ',     category: TileCategory.creature, gridIndex: 5),
  ThemeDefinition(id: 'crust_st_orangutan',  name: 'オラウータンクラブ',       category: TileCategory.creature, gridIndex: 6),
  ThemeDefinition(id: 'crust_st_otohime',    name: 'オトヒメエビ',             category: TileCategory.creature, gridIndex: 7),
  ThemeDefinition(id: 'crust_st_nadeshiko',  name: 'ナデシコカクレエビ',       category: TileCategory.creature, gridIndex: 8),
  ThemeDefinition(id: 'crust_st_asahi_gani', name: 'アサヒガニ',               category: TileCategory.creature, gridIndex: 9),
  ThemeDefinition(id: 'crust_st_monhana',    name: 'モンハナシャコ',           category: TileCategory.creature, gridIndex: 10),
  ThemeDefinition(id: 'crust_st_clear',      name: 'クリアクリーナーシュリンプ', category: TileCategory.creature, gridIndex: 11),
  ThemeDefinition(id: 'crust_st_free',       name: '⭐ 自由枠',                category: TileCategory.creature, gridIndex: 12),
  ThemeDefinition(id: 'crust_st_kikuchi',    name: 'キクチカニダマシ',         category: TileCategory.creature, gridIndex: 13),
  ThemeDefinition(id: 'crust_st_hakusen',    name: 'ハクセンエビ',             category: TileCategory.creature, gridIndex: 14),
  ThemeDefinition(id: 'crust_st_akahoshi',   name: 'アカホシカクレエビ',       category: TileCategory.creature, gridIndex: 15),
  ThemeDefinition(id: 'crust_st_isogiebi',   name: 'イソギンチャクエビ',       category: TileCategory.creature, gridIndex: 16),
  ThemeDefinition(id: 'crust_st_akahoshi_kani', name: 'アカホシカニダマシ',   category: TileCategory.creature, gridIndex: 17),
  ThemeDefinition(id: 'crust_st_pink_squad', name: 'ピンクスクワッドロブスター', category: TileCategory.creature, gridIndex: 18),
  ThemeDefinition(id: 'crust_st_oshare',     name: 'オシャレカクレエビ',       category: TileCategory.creature, gridIndex: 19),
  ThemeDefinition(id: 'crust_st_soriashi',   name: 'ソリハシコモンエビ',       category: TileCategory.creature, gridIndex: 20),
  ThemeDefinition(id: 'crust_st_violet',     name: 'バイオレットボクサーシュリンプ', category: TileCategory.creature, gridIndex: 21),
  ThemeDefinition(id: 'crust_st_koshiori',   name: 'コシオリエビ',             category: TileCategory.creature, gridIndex: 22),
  ThemeDefinition(id: 'crust_st_nise_aka',   name: 'ニセアカホシカクレエビ',   category: TileCategory.creature, gridIndex: 23),
  ThemeDefinition(id: 'crust_st_oo_akahoshi',name: 'オオアカホシサンゴガニ',   category: TileCategory.creature, gridIndex: 24),
];

// 甲殻類 意外と人気な地味子ちゃん
const List<ThemeDefinition> kCrustaceanHiddenThemes = [
  ThemeDefinition(id: 'crust_hd_bishamon',   name: 'ビシャモンエビ',           category: TileCategory.creature, gridIndex: 0),
  ThemeDefinition(id: 'crust_hd_goshiki',    name: 'ゴシキエビ',               category: TileCategory.creature, gridIndex: 1),
  ThemeDefinition(id: 'crust_hd_iboiso',     name: 'イボイソバナガニ',         category: TileCategory.creature, gridIndex: 2),
  ThemeDefinition(id: 'crust_hd_kagero',     name: 'カゲロウカクレエビ',       category: TileCategory.creature, gridIndex: 3),
  ThemeDefinition(id: 'crust_hd_warekara',   name: 'ワレカラ',                 category: TileCategory.creature, gridIndex: 4),
  ThemeDefinition(id: 'crust_hd_hitode',     name: 'ヒトデヤドリエビ',         category: TileCategory.creature, gridIndex: 5),
  ThemeDefinition(id: 'crust_hd_kudayagi',   name: 'クダヤギクモエビ',         category: TileCategory.creature, gridIndex: 6),
  ThemeDefinition(id: 'crust_hd_kaikamuri',  name: 'カイカムリ',               category: TileCategory.creature, gridIndex: 7),
  ThemeDefinition(id: 'crust_hd_komachi',    name: 'コマチコシオリエビ',       category: TileCategory.creature, gridIndex: 8),
  ThemeDefinition(id: 'crust_hd_gangaze',    name: 'ガンガゼカクレエビ',       category: TileCategory.creature, gridIndex: 9),
  ThemeDefinition(id: 'crust_hd_zara',       name: 'ザラカイメンカクレエビ',   category: TileCategory.creature, gridIndex: 10),
  ThemeDefinition(id: 'crust_hd_kanzashi',   name: 'カンザシヤドカリ',         category: TileCategory.creature, gridIndex: 11),
  ThemeDefinition(id: 'crust_hd_free',       name: '⭐ 自由枠',                category: TileCategory.creature, gridIndex: 12),
  ThemeDefinition(id: 'crust_hd_umiushi',    name: 'ウミウシカクレエビ',       category: TileCategory.creature, gridIndex: 13),
  ThemeDefinition(id: 'crust_hd_muchi',      name: 'ムチカラマツエビ',         category: TileCategory.creature, gridIndex: 14),
  ThemeDefinition(id: 'crust_hd_mokuzushoi', name: 'モクズショイ',             category: TileCategory.creature, gridIndex: 15),
  ThemeDefinition(id: 'crust_hd_basara',     name: 'バサラカクレエビ',         category: TileCategory.creature, gridIndex: 16),
  ThemeDefinition(id: 'crust_hd_ortoman',    name: 'オルトマンワラエビ',       category: TileCategory.creature, gridIndex: 17),
  ThemeDefinition(id: 'crust_hd_togetsu',    name: 'トゲツノメエビ',           category: TileCategory.creature, gridIndex: 18),
  ThemeDefinition(id: 'crust_hd_kotobuki',   name: 'コトブキテッポウエビ',     category: TileCategory.creature, gridIndex: 19),
  ThemeDefinition(id: 'crust_hd_semi',       name: 'セミエビ',                 category: TileCategory.creature, gridIndex: 20),
  ThemeDefinition(id: 'crust_hd_anamori',    name: 'アナモリチュウコシオリエビ', category: TileCategory.creature, gridIndex: 21),
  ThemeDefinition(id: 'crust_hd_yokoebi',    name: 'ヨコエビ',                 category: TileCategory.creature, gridIndex: 22),
  ThemeDefinition(id: 'crust_hd_iso_kompei', name: 'イソコンペイトウガニ',     category: TileCategory.creature, gridIndex: 23),
  ThemeDefinition(id: 'crust_hd_sarasa',     name: 'サラサエビ',               category: TileCategory.creature, gridIndex: 24),
];

// 全追加シートのマップ
const Map<String, List<ThemeDefinition>> kExtraSheetThemesMap = {
  'ishigaki':           kIshigakiThemes,
  'izu':                kIzuThemes,
  'macro':              kMacroThemes,
  'wide':               kWideThemes,
  'kushimoto':          kKushimotoThemes,
  'kashiwajima':        kKashiwajimaThemes,
  'deep':               kDeepThemes,
  'hanadi':             kHanadiThemes,
  'nudibranch_iro':     kNudibranchIroThemes,
  'nudibranch_other':   kNudibranchOtherThemes,
  'goby_bingo':         kGobyBingoThemes,
  'crustacean_standard':kCrustaceanStandardThemes,
  'crustacean_hidden':  kCrustaceanHiddenThemes,
};
